name: release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Bundle xk6 extensions
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        id: build
        uses: szkiba/xk6bundler@v0
        with:
          with: github.com/grafana/xk6-python=/github/workspace

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
